name: CI/CD Pipeline AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Compilar y subir la imagen (Push)
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mi-app-web:latest

    - name: Conectar a EC2 y Desplegar
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mi-app-web:latest
          docker stop mi-web || true
          docker rm mi-web || true
          docker run -d --name mi-web -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/mi-app-web:latest
          sleep 5
          curl --fail --silent http://localhost || (echo "La web no responde" && exit 1)
          echo "Despliegue completado"